POST http://localhost:9092/oauth/token?grant_type=password&username=admin&password=123456
Content-Type: application/json
Authorization: Basic Y29kZXJlZjokMmEkMTAkcDlQazBmUU5BUVNlc0k0dnV2S0EwT1phbkREMg==

###

GET http://localhost:9595/api/catalog/product HTTP/1.1
Content-Type: application/json
Authorization: Bearer 295d1e56-b081-4862-85ec-66d7473553be

###

POST http://localhost:9595/api/catalog/product HTTP/1.1
Content-Type: application/json
Authorization: Bearer 295d1e56-b081-4862-85ec-66d7473553be

{
    "name": "Product name",
    "description": "Product description"
}

###

GET http://localhost:9094/product